---
driver:
  name: vagrant
  # network:
  #   - [ "forwarded_port", { guest: 4440, host: 4440 } ]

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.2
  # TODO: ubuntu support
  # - name: ubuntu-14.04
  #   run_list:
  #     - recipe[apt]
  # - name: ubuntu-16.04
  #   run_list:
  #     - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[rundeck_2::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
