source 'https://rubygems.org'

gem 'berkshelf'
gem 'chef'
gem 'chefspec'
gem 'foodcritic'
gem 'inspec'
gem 'kitchen-docker'
gem 'kitchen-inspec'
gem 'kitchen-vagrant'
gem 'rake'
gem 'rubocop'
gem 'stove'
gem 'test-kitchen'
